name: WASM Build

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Conan
      uses: conan-io/setup-conan@v1

    - name: Build project
      run: |
        mkdir build
        cd build
        conan install .. --build=missing -s build_type=Release -pr ../web/conan_profile
        source ./Release/generators/conanbuild.sh
        cmake .. -DCMAKE_TOOLCHAIN_FILE=Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Cleanup to specific files only
      run: |
        cd build
        find . -type f ! -name 'index.html' ! -name 'OrbitSimulation.wasm' ! -name 'OrbitSimulation.js' ! -name 'OrbitSimulation.data' ! -name 'coi-serviceworker.js' -delete
        find . -type d -empty -delete

    - name: Deploy to target repo Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: ./build
        external_repository: toastyy-1/toastyy-1.github.io
        publish_branch: main
        force_orphan: true
